# https://taskfile.dev

version: "3"

vars:
  ROOT_DIR: "{{.TASKFILE_DIR}}"
  KERNEL_VERSION: 6.12.10
  KERNEL_TAR: linux-{{.KERNEL_VERSION}}.tar.xz
  KERNEL_URL: https://cdn.kernel.org/pub/linux/kernel/v6.x/{{.KERNEL_TAR}}
  KERNEL_SRC_DIR: components/kernel
  BB_VERSION: 1.37.0
  BB_TAR: busybox-{{.BB_VERSION}}.tar.bz2
  BB_URL: https://busybox.net/downloads/{{.BB_TAR}}
  BB_SRC_DIR: components/busybox
  INITRAMFS_DIR: components/initramfs

tasks:
  download_kernel:
    cmds:
      - task: clean_kernel
      - echo "Downloading Linux kernel source..."
      - wget -c {{.KERNEL_URL}} -O {{.KERNEL_SRC_DIR}}/{{.KERNEL_TAR}}
      - echo "Extracting Linux kernel source..."
      - tar -xf {{.KERNEL_SRC_DIR}}/{{.KERNEL_TAR}} -C {{.KERNEL_SRC_DIR}} --strip-components=1
      - echo "Linux kernel source ready in {{.KERNEL_SRC_DIR}}."
    status:
      - test -d {{.KERNEL_SRC_DIR}}

  clean_kernel:
    cmds:
      - rm -rf {{.KERNEL_SRC_DIR}}

  config_kernel:
    dir: "{{.KERNEL_SRC_DIR}}"
    cmds:
      - make mrproper
      - make tinyconfig
      - scripts/config --enable CONFIG_PRINTK
      - scripts/config --enable CONFIG_EARLY_PRINTK
      - scripts/config --enable CONFIG_TTY
      - scripts/config --enable CONFIG_BLK_DEV_INITRD
      - scripts/config --enable CONFIG_BINFMT_ELF
      - scripts/config --enable CONFIG_BINFMT_SCRIPT
      - scripts/config --enable CONFIG_64BIT
      - make olddefconfig

  compile_kernel:
    dir: "{{.KERNEL_SRC_DIR}}"
    cmds:
      - task: config_kernel
      - make -j$(nproc)

  run_kernel:
    dir: "{{.KERNEL_SRC_DIR}}"
    cmds:
      - task: compile_kernel
      - task: create_initramfs
      - qemu-system-x86_64 -kernel arch/x86/boot/bzImage -initrd ../initramfs.cpio.gz

  download_busybox:
    cmds:
      - task: clean_busybox
      - echo "Downloading Busybox source..."
      - wget -c {{.BB_URL}} -O {{.BB_SRC_DIR}}/{{.BB_TAR}}
      - echo "Extracting Busybox source..."
      - tar -xf {{.BB_SRC_DIR}}/{{.BB_TAR}} -C {{.BB_SRC_DIR}} --strip-components=1
      - echo "Busybox source ready in {{.BB_SRC_DIR}}."
    status:
      - test -d {{.BB_SRC_DIR}}

  clean_busybox:
    cmds:
      - rm -rf {{.BB_SRC_DIR}}

  config_busybox:
    dir: "{{.BB_SRC_DIR}}"
    cmds:
      - make defconfig
      - sed -i 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/' .config
      - sed -i 's/CONFIG_TC=y/CONFIG_TC=n/' .config

  compile_busybox:
    dir: "{{.BB_SRC_DIR}}"
    cmds:
      - task: config_busybox
      - make -j$(nproc) busybox
      - mkdir -p ../initramfs/{bin,sbin,usr/bin,usr/sbin}
      - cp busybox ../initramfs/bin/busybox

  create_initramfs:
    dir: "{{.INITRAMFS_DIR}}"
    cmds:
      - task: compile_busybox
      - rm ../initramfs.cpio.gz
      - find . -print0 | cpio --null --create --verbose --format=newc | gzip --best > ../initramfs.cpio.gz
