# https://taskfile.dev

version: "3"

vars:
  ROOT_DIR: "{{.TASKFILE_DIR}}"
  KERNEL_VERSION: 6.12.10
  KERNEL_TAR: linux-{{.KERNEL_VERSION}}.tar.xz
  KERNEL_URL: https://cdn.kernel.org/pub/linux/kernel/v6.x/{{.KERNEL_TAR}}
  KERNEL_SRC_DIR: components/kernel
  BB_VERSION: 1.37.0
  BB_TAR: busybox-{{.BB_VERSION}}.tar.bz2
  BB_URL: https://busybox.net/downloads/{{.BB_TAR}}
  BB_SRC_DIR: components/busybox
  INITRAMFS_DIR: components/initramfs
  INITRAMFS_FILE: components/initramfs.cpio.gz

tasks:
  download_kernel:
    cmds:
      - echo "Downloading Linux kernel source..."
      - wget -c {{.KERNEL_URL}} -O {{.KERNEL_SRC_DIR}}/{{.KERNEL_TAR}}
      - echo "Extracting Linux kernel source..."
      - tar -xf {{.KERNEL_SRC_DIR}}/{{.KERNEL_TAR}} -C {{.KERNEL_SRC_DIR}} --strip-components=1
      - echo "Linux kernel source ready in {{.KERNEL_SRC_DIR}}."
    status:
      - test -d {{.KERNEL_SRC_DIR}}

  clean_kernel:
    cmds:
      - rm -rf {{.KERNEL_SRC_DIR}}
    status:
      - test ! -d {{.KERNEL_SRC_DIR}}

  config_kernel:
    dir: "{{.KERNEL_SRC_DIR}}"
    cmds:
      - make mrproper
      - make tinyconfig
      - scripts/config --enable CONFIG_PRINTK
      - scripts/config --enable CONFIG_EARLY_PRINTK
      - scripts/config --enable CONFIG_TTY
      - scripts/config --enable CONFIG_BLK_DEV_INITRD
      - scripts/config --enable CONFIG_BINFMT_ELF
      - scripts/config --enable CONFIG_BINFMT_SCRIPT
      - scripts/config --enable CONFIG_PROC_FS
      - scripts/config --enable CONFIG_SYSFS
      - scripts/config --enable CONFIG_64BIT
      - make olddefconfig
    status:
      - test -f .config

  compile_kernel:
    dir: "{{.KERNEL_SRC_DIR}}"
    cmds:
      - task: config_kernel
      - make -j$(nproc)
    sources:
      - /**/*.c
      - .config
    generates:
      - arch/x86/boot/bzImage

  download_busybox:
    cmds:
      - echo "Downloading Busybox source..."
      - wget -c {{.BB_URL}} -O {{.BB_SRC_DIR}}/{{.BB_TAR}}
      - echo "Extracting Busybox source..."
      - tar -xf {{.BB_SRC_DIR}}/{{.BB_TAR}} -C {{.BB_SRC_DIR}} --strip-components=1
      - echo "Busybox source ready in {{.BB_SRC_DIR}}."
    status:
      - test -d {{.BB_SRC_DIR}}

  clean_busybox:
    cmds:
      - rm -rf {{.BB_SRC_DIR}}
    status:
      - test ! -d {{.BB_SRC_DIR}}

  config_busybox:
    dir: "{{.BB_SRC_DIR}}"
    cmds:
      - make defconfig
      - sed -i 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/' .config
      - sed -i 's/CONFIG_TC=y/CONFIG_TC=n/' .config

  compile_busybox:
    dir: "{{.BB_SRC_DIR}}"
    cmds:
      - task: config_busybox
      - make -j$(nproc) busybox
    sources:
      - /**/*.c
    creates:
      - busybox

  create_initramfs:
    cmds:
      - mkdir -p {{.INITRAMFS_DIR}}/{bin,sbin,usr/bin,usr/sbin}

  clean_initramfs:
    cmds:
      - rm {{.INITRAMFS_DIR}}/bin/busybox
      - rm {{.INITRAMFS_FILE}}
    status:
      - test ! -f {{.INITRAMFS_DIR}}/bin/busybox
      - test ! -f {{.INITRAMFS_FILE}}

  package_initramfs:
    cmds:
      - task: compile_busybox
      - task: create_initramfs
      - task: clean_initramfs
      - cp {{.BB_SRC_DIR}}/busybox {{.INITRAMFS_DIR}}/bin/busybox
      - (cd {{.INITRAMFS_DIR}} && find . -print0 | cpio --null --create --verbose --format=newc | gzip --best) > "{{.INITRAMFS_FILE}}"

  run:
    cmds:
      - task: compile_kernel
      - task: package_initramfs
      - qemu-system-x86_64 -kernel {{.KERNEL_SRC_DIR}}/arch/x86/boot/bzImage -initrd {{.INITRAMFS_FILE}}

  clean:
    cmds:
      - task: clean_kernel
      - task: clean_busybox
      - task: clean_initramfs
