# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list--all

  clean:
    cmds:
      - echo "Cleaning with KDIR {{.KDIR}}"
      - make V=1 clean KDIR="{{.KDIR}}" -j$(nproc)

  build:
    cmds:
      - echo "Building with KDIR {{.KDIR}}"
      - rustup install $("{{.KDIR}}"/scripts/min-tool-version.sh rustc)
      - rustup override set $("{{.KDIR}}"/scripts/min-tool-version.sh rustc)
      - rustup component add rust-src
      - make RUSTC=$(which rustc) KDIR="{{.KDIR}}" -j$(nproc)
