version: '3'

tasks:
  clean:
    cmds:
      - echo "Cleaning with KDIR {{.KDIR}}"
      - make V=1 clean KDIR="{{.KDIR}}" -j$(nproc)

  build:
    cmds:
      - echo "Building with KDIR {{.KDIR}}"
      - rustup install 1.83.0
      - rustup override set 1.83.0
      - rustc --version
      - export RUSTFLAGS="-Zbuild-std=core,alloc"
      - make V=1 RUSTC=$(which rustc) all KDIR="{{.KDIR}}" -j$(nproc)
